language: ruby
cache: bundler

rvm:
  - 2.3.1

env:
  global:
    - APP_HOST='test.travis.lc'
    - MAIL_SENDER='noreply@travis.lc'
    - MANDRILL_APIKEY='SECRET'
    - MANDRILL_USERNAME='SECRET'
    - PAPPER='37df6445cf70c637cbf2bb07e51e423b507ee90'
    - SECRET_KEY='37df6445cf70c637cbf2bb07e51e423b507ee90'
    - SECRET_KEY_BASE='37df6445cf70c637cbf2bb07e51e423b507ee90'
    - SECRET_TOKEN='37df6445cf70c637cbf2bb07e51e423b507ee90'
    - DEFAULT_URL_OPTIONS='http://test.travis.lc'

script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
  - bundle exec rake

before_script:
  - cp config/database.travis.yml config/database.yml

addons:
  code_climate:
    repo_token: cb2f7c4fd22ace4926202598606e5e86587717ed03d66964cd02ae9ef24a4f6e
