default: &default
  app_host:            <%= ENV['APP_HOST'] %>
  secret_key_base:     <%= ENV['SECRET_KEY_BASE'] %>
  secret_key:          <%= ENV['SECRET_KEY'] %>
  secret_token:        <%= ENV['SECRET_TOKEN'] %>
  pepper:              <%= ENV['PEPPER'] %>
  mailer_sender:       <%= ENV['MAIL_SENDER'] %>
  default_url_options: <%= ENV['DEFAULT_URL_OPTIONS'] %>
  errbit:
    key:               <%= ENV['ERRBIT_KEY'] %>
    host:              <%= ENV['ERRBIT_HOST'] %>

production:
  <<: *default

development:
  <<: *default

test:
  <<: *default
